# Copyright 2024 Hauki Tech sp. z o.o.
# SPDX-License-Identifier: Apache-2.0
formatter: markdown table
header-from: terraform.tf
output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}
