name: Terraform docs

on:
  pull_request:

jobs:
  check_docs_up_to_date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Docs for all modules
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          find-dir: .
          config-file: .terraform-docs.yml
          output-method: ""
          template: ""
          fail-on-diff: true
