# Copyright 2024 Hauki Tech sp. z o.o.
# SPDX-License-Identifier: Apache-2.0

on:
  - push

env:
  terraform_version: 1.10
  terragrunt_version: 0.72

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.terraform_version }}
          tg_version: ${{ env.terragrunt_version }}
          tg_dir: ${{ github.workspace }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
      - run: terraform fmt -check --recursive -diff .
