# Copyright 2024 Hauki Tech sp. z o.o.
# SPDX-License-Identifier: Apache-2.0

name: Tflint

on:
  pull_request:

jobs:
  check_errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
      - name: Check errors in configuration
        uses: terraform-linters/tflint-load-config-action@v1
        with:
         source-repo: ./
      - run: tflint -f compact
